name: _body_only
timestamp: 1629978546
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1629828473
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4372: 'System Messages'
  hero-slider:
    hero-slider-4314: 'Hero Slider'
  content:
    system-content-4124: 'Page Content'
  gallery:
    gallery-6800: Gallery
  logo:
    logo-6480: 'Logo / Image'
    logo-4071: 'Logo / Image'
    logo-1364: 'Logo / Image'
inherit: {  }
