name: 11
timestamp: 1630929780
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1517560458
positions: {  }
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  breadcrumb: Breadcrumb
  fullwidth: Fullwidth
  showcase: Showcase
  intro: Intro
  feature: Feature
  subfeature: Subfeature
  utility: Utility
  maintop: Maintop
  system-messages: System-messages
  sidebar: Sidebar
  mainbody: Mainbody
  mainbottom: Mainbottom
  extension: Extension
  additional: Additional
  prebottom: Prebottom
  bottom: Bottom
  afterbottom: Afterbottom
  last: Last
  copyright: Copyright
  to-top: To-top
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles: {  }
inherit:
  default:
    drawer: drawer
    top: top
    navigation: navigation
    breadcrumb: breadcrumb
    showcase: showcase
    feature: feature
    utility: utility
    maintop: maintop
    sidebar: sidebar
    mainbottom: mainbottom
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
